### ISSUE TITLE
Model Weights Request

### ISSUE THREAD

**Issue by weizhepei** [xiangrongzeng/multi_re#1]
Hi Xiangrong, I'm trying to reproduce the results of your excellent work but failed to achieve the same performance as reported in the EMNLP-19 [paper](https://www.aclweb.org/anthology/D19-1035.pdf). Would it be possible for you to make the well-trained model weights (i.e., the weights that lead to 0.721 F1 in NYT and 0.616 F1 in WebNLG) publicly available? Thank you for your consideration.

**Comment by xiangrongzeng** [comment]
The model weights are not in my hand row. I have reached such perfromance most of the time (but not every time, sometimes the performance dropped a lot suddenly). Please pretrain the model with NLL training. When the performance of the pretrained model achieves about 80% of the best NLL performance, training the model with RL loss.
